Feature/adding links of internal pages
estartando-devs/site pull request #113
Opened 2022-03-24 01:47 UTC by jonataspinto

### [Ticket]() | [Mocks]()

## Description

Provide a description of what was changed and why it was implemented this way.

## Dev Notes

Com a remoção da seção de inscreva-se estávamos sem link para `perguntas-frequentes`. Nesse pr adiciono o mesmo link no footer e link para home nas logos.

## Screenshots / Videos
![image](https://user-images.githubusercontent.com/34426836/159825355-fe8e78ef-16c0-4403-ab10-9cf7b7c183b6.png)

![image](https://user-images.githubusercontent.com/34426836/159825263-fb945df7-30e9-434c-94b1-b02c5c014c20.png)
## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-03-24 01:49 UTC, estartandodevs commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.84 | ✅ |
| First Contentful Paint | 1.6 s |  |
| Time to Interactive | 7.8 s |  |
| Speed Index | 3.1 s |  |
| Total Blocking Time | 330 ms |  |
| Largest Contentful Paint | 2.5 s |  |
| Cumulative Layout Shift | 0.021 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.8 | ✅ |
| First Contentful Paint | 2.7 s |  |
| Time to Interactive | 7.2 s |  |
| Speed Index | 4.0 s |  |
| Total Blocking Time | 170 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-24 01:49 UTC, estartandodevs reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-82-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-91-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-75-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-80-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-24 01:50 UTC, ramonxm requested changes

2022-03-24 01:50 UTC, ramonxm commented on src/components/CommonQuestions/index.tsx
> +        <a>
Nesse caso não precisa da tag `a` visto que não ta utilizando o `_blank`,  correto?

2022-03-24 01:50 UTC, ramonxm commented on src/components/Footer/index.tsx
> +        <a>
Mesma coisa.

2022-03-24 01:57 UTC, jonataspinto commented on src/components/CommonQuestions/index.tsx
> +        <a>
Infelizmente sim, olha os erros ao tentar usar sem.

https://nextjs.org/docs/messages/link-passhref

![image](https://user-images.githubusercontent.com/34426836/159826181-dc28fd97-7427-473f-a251-8b859d3d90e6.png)

![image](https://user-images.githubusercontent.com/34426836/159826487-7eb5a3b5-1a69-4b5d-8ef6-66455395753e.png)

2022-03-24 11:54 UTC, ramonxm commented on src/components/CommonQuestions/index.tsx
> +        <a>
I see, seguimos.

2022-03-24 11:54 UTC, ramonxm approved these changes
LGTM

2022-03-24 21:45 UTC, estartandodevs commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.67 | ✅ |
| First Contentful Paint | 1.2 s |  |
| Time to Interactive | 7.8 s |  |
| Speed Index | 3.8 s |  |
| Total Blocking Time | 420 ms |  |
| Largest Contentful Paint | 4.6 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.8 | ✅ |
| First Contentful Paint | 2.6 s |  |
| Time to Interactive | 7.1 s |  |
| Speed Index | 4.1 s |  |
| Total Blocking Time | 170 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-24 21:46 UTC, estartandodevs reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-81-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-91-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-75-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-79-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-26 00:51 UTC, estartandodevs commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.33 | ✅ |
| First Contentful Paint | 3.1 s |  |
| Time to Interactive | 9.2 s |  |
| Speed Index | 6.1 s |  |
| Total Blocking Time | 1,260 ms |  |
| Largest Contentful Paint | 6.2 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.86 | ✅ |
| First Contentful Paint | 2.4 s |  |
| Time to Interactive | 5.7 s |  |
| Speed Index | 3.6 s |  |
| Total Blocking Time | 110 ms |  |
| Largest Contentful Paint | 3.1 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-26 00:51 UTC, estartandodevs reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-82-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-75-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-80-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-93-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-26 00:51 UTC, merged