Feature/list of approved
estartando-devs/site pull request #123
Opened 2022-04-01 20:51 UTC by joaoprferreira

### [Ticket]() | [Mocks]()

## Description

Construir os serviços para consumir a lista de alunos aprovados.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-04-01 22:41 UTC, ramonxm requested changes

2022-04-01 22:41 UTC, ramonxm commented on src/pages/index.tsx
> +  console.log(props);
remover log

2022-04-01 22:41 UTC, ramonxm commented on src/services/getSiteData.ts
> +    (data) => data.json()
isso aqui funcionou? o certo seria

```js
.then(async (data) => await data.json())
```

2022-04-01 22:44 UTC, ramonxm commented
Não sei se isso aqui é um draft, mas o build falhou:
https://github.com/estartando-devs/site/runs/5794497907?check_suite_focus=true

2022-04-02 01:16 UTC, henriquecalenzoo approved these changes

2022-04-02 01:21 UTC, yagovaluchedevs commented on src/pages/index.tsx
> +  console.log(props);
remover o ponto e parênteses

2022-04-02 01:56 UTC, jonataspinto approved these changes

2022-04-02 01:57 UTC, estartandodevs commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.72 | ✅ |
| First Contentful Paint | 1.3 s |  |
| Time to Interactive | 7.7 s |  |
| Speed Index | 2.2 s |  |
| Total Blocking Time | 690 ms |  |
| Largest Contentful Paint | 3.0 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.85 | ✅ |
| First Contentful Paint | 2.3 s |  |
| Time to Interactive | 6.9 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 190 ms |  |
| Largest Contentful Paint | 2.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-04-02 01:57 UTC, estartandodevs reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-80-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-75-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-73-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-93-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? **GitHub runners could be the cause.**
[Try running on Foo instead](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-04-02 01:57 UTC, estartandodevs commented
**Size Change:** 0 B 🆕

**Total Size:** 0 B



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

2022-04-02 01:58 UTC, henriquecalenzoo approved these changes

2022-04-02 02:06 UTC, merged