List approved
estartando-devs/site pull request #127
Opened 2022-04-02 05:21 UTC by henriquecalenzoo

### [Ticket]() | [Mocks]()// No ticket

## Description

Created the component to list of approved and integrate with backend response

## Dev Notes

- If any developer notes are required, list them here. If not, remove the 'Notes' section.

## Testing

### Steps

1. List all steps in a numbered list

## Screenshots / Videos

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-04-03 00:55 UTC, jonataspinto requested changes
Vamoss

2022-04-03 00:55 UTC, jonataspinto commented on src/components/Approved/BannerApproved/index.tsx
> +        <LinkWrapper color="white" href="#approved-list">
Acho que pode manter como resultado.

2022-04-03 00:55 UTC, jonataspinto commented on src/components/ListApprovedCourses/styles.ts
> +export const ListApprovedContainer = styled.div``;
Estávamos ciando os containers com `section`. Agrega valor semantico.

2022-04-03 00:55 UTC, jonataspinto commented on src/components/ListApprovedCourses/styles.ts
> +  gap: 10px;
Use rem 😊

Uma dica se não souber é só calcular o valor que vc quer em px, por nossa base para o rem que é 16px.

Ex: 

10 / 16 = 0.265 rem

2022-04-03 00:55 UTC, jonataspinto commented on src/components/ListApprovedCourses/styles.ts
> +export const CourseContainer = styled.section`
Aqui já não é section. A seção e o pai que agrupa todos esses.

2022-04-04 12:08 UTC, jonataspinto commented on src/components/Approved/BannerApproved/index.tsx
> +        <LinkWrapper color="white" href="#approved-list">
portuga mesmo.

2022-04-04 12:31 UTC, estartandodevs reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-86-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-75-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-86-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-93-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? **GitHub runners could be the cause.**
[Try running on Foo instead](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-04-04 12:32 UTC, estartandodevs commented
**Size Change:** 0 B 🆕

**Total Size:** 0 B



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

2022-04-04 12:42 UTC, henriquecalenzoo commented on src/components/ListApprovedCourses/styles.ts
> +export const CourseContainer = styled.section`
Mas esse cara engloba todos.

2022-04-04 12:49 UTC, henriquecalenzoo commented on src/components/ListApprovedCourses/styles.ts
> +export const CourseContainer = styled.section`
Entendi o que quis dizer.

2022-04-04 12:51 UTC, estartandodevs commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.6 | ✅ |
| First Contentful Paint | 1.2 s |  |
| Time to Interactive | 6.9 s |  |
| Speed Index | 1.9 s |  |
| Total Blocking Time | 650 ms |  |
| Largest Contentful Paint | 5.1 s |  |
| Cumulative Layout Shift | 0.021 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.86 | ✅ |
| First Contentful Paint | 2.3 s |  |
| Time to Interactive | 6.9 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 130 ms |  |
| Largest Contentful Paint | 2.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-04-04 12:51 UTC, ramonxm approved these changes
LGTM

2022-04-04 12:51 UTC, estartandodevs reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-53-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-75-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-80-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-93-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? **GitHub runners could be the cause.**
[Try running on Foo instead](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-04-04 12:52 UTC, estartandodevs commented
**Size Change:** 0 B 🆕

**Total Size:** 0 B



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

2022-04-04 12:54 UTC, merged