[FEATURE] Header
estartando-devs/site pull request #43
Opened 2022-02-25 21:26 UTC by ramonxm

### [Ticket](https://trello.com/c/brWLTzPa/29-component-header)

## Description

Criação da Header da aplicação
\

## Screenshots / Videos

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/38158476/155805208-5b8bdf7a-31b3-438c-9a81-2a0dabd60e08.png">

## Developer Checks

- [X] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [X] Tested on browser device
- [X] Tested on Mobile device

2022-02-25 21:28 UTC, jonataspinto commented
PQP 31 files

2022-02-25 21:29 UTC, jonataspinto commented
depois do carnaval eu termino 😆

2022-02-25 21:29 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-92-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-80-orange?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-95-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-83-orange?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-02-25 21:29 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.55 | ✅ |
| First Contentful Paint | 3.7 s |  |
| Time to Interactive | 6.5 s |  |
| Speed Index | 4.8 s |  |
| Total Blocking Time | 620 ms |  |
| Largest Contentful Paint | 4.3 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.97 | ✅ |
| First Contentful Paint | 1.4 s |  |
| Time to Interactive | 4.8 s |  |
| Speed Index | 2.3 s |  |
| Total Blocking Time | 120 ms |  |
| Largest Contentful Paint | 1.4 s |  |
| Cumulative Layout Shift | 0.004 |  |

    
</details>

2022-02-25 21:34 UTC, jonataspinto requested changes

2022-02-25 21:34 UTC, jonataspinto commented on src/components/Header/styles.ts
> +  max-width: 100%;
width somente não?

2022-02-25 21:34 UTC, jonataspinto commented on src/components/Header/styles.ts
> +  align-items: flex-start;
display flex já é start nos eixos

2022-02-25 21:34 UTC, jonataspinto commented on src/components/LinkWrapper/styles.ts
> +  font-size: ${convertPxToRem(17)};
achei que iria remover.

2022-02-25 21:45 UTC, ramonxm commented on src/components/Header/styles.ts
> +  align-items: flex-start;
sim, esqueci de tirar isso ai

2022-02-25 21:50 UTC, ramonxm commented on src/components/LinkWrapper/styles.ts
> +  font-size: ${convertPxToRem(17)};
deixar só no global?

2022-02-25 21:51 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.62 | ✅ |
| First Contentful Paint | 3.1 s |  |
| Time to Interactive | 4.8 s |  |
| Speed Index | 4.7 s |  |
| Total Blocking Time | 470 ms |  |
| Largest Contentful Paint | 4.9 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.2 s |  |
| Speed Index | 2.7 s |  |
| Total Blocking Time | 80 ms |  |
| Largest Contentful Paint | 2.2 s |  |
| Cumulative Layout Shift | 0.011 |  |

    
</details>

2022-02-25 21:51 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-93-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-80-orange?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-96-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-83-orange?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-02-26 00:13 UTC, jonataspinto commented on src/components/LinkWrapper/styles.ts
> +  font-size: ${convertPxToRem(17)};
falo do convertPxToRem

2022-02-26 00:43 UTC, jonataspinto approved these changes
LGTM

2022-02-26 00:44 UTC, jonataspinto commented
> ![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-93-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-80-orange?style=flat-square) 
> | Device | URL |
> |--|--|
> | desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |
> 
> ![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-96-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-83-orange?style=flat-square) 
> | Device | URL |
> |--|--|
> | mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |
> 
> Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
> If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
> <!-- generated by lighthouse-check -->
> <!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

@ramonxm pwa subiu um cadinho 🤔

2022-02-26 00:45 UTC, jonataspinto commented
Merregeeeeeee

2022-02-26 00:46 UTC, merged