feat/our-results
estartando-devs/site pull request #45
Opened 2022-02-26 22:30 UTC by henriquecalenzoo

### [Ticket]() | [Mocks]()

## Description

Provide a description of what was changed and why it was implemented this way.

## Dev Notes

- If any developer notes are required, list them here. If not, remove the 'Notes' section.

## Testing

### Steps

1. List all steps in a numbered list

## Screenshots / Videos

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-02-26 22:39 UTC, ramonxm requested changes

2022-02-27 00:05 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-87-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-80-orange?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-95-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-83-orange?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-02-27 00:08 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.74 | ✅ |
| First Contentful Paint | 2.8 s |  |
| Time to Interactive | 4.2 s |  |
| Speed Index | 3.4 s |  |
| Total Blocking Time | 310 ms |  |
| Largest Contentful Paint | 4.6 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 1.6 s |  |
| Time to Interactive | 5.3 s |  |
| Speed Index | 2.7 s |  |
| Total Blocking Time | 180 ms |  |
| Largest Contentful Paint | 1.9 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-02-27 00:08 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-92-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-80-orange?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-94-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-91-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-83-orange?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-02-27 01:35 UTC, joaoprferreira commented on src/styles/theme.tsx
> +  },
Boaaaa

2022-02-27 02:41 UTC, merged