Feature/student profile
estartando-devs/site pull request #58
Opened 2022-03-02 02:35 UTC by joaoprferreira

### [Ticket]()https://trello.com/c/7JQ3bPGd/24-cria%C3%A7%C3%A3o-componente-de-perfil-do-aluno | [Mocks]()

## Description

eu fiz componente de Perfil do aluno

Provide a description of what was changed and why it was implemented this way.

## Testing

### Steps

1. List all steps in a numbered list

## Screenshots / Videos

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

![image](https://user-images.githubusercontent.com/49590645/156283817-dd7473bf-1ee5-4630-b268-85e7f2159c99.png)

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-03-02 11:43 UTC, ramonxm requested changes

2022-03-02 11:43 UTC, ramonxm commented on src/components/StudentProfile/index.tsx
> +        <div>
Div se faz necessário?

2022-03-02 11:43 UTC, ramonxm commented on src/components/StudentProfile/index.tsx
> +            key={index}
Por enquanto podemos deixar assim, mas podemos pensar em uma alternativa melhor ao index

2022-03-02 11:43 UTC, ramonxm commented on src/components/StudentProfile/styles.ts
> +  width: 585px;
Use medidas relativas

2022-03-02 11:43 UTC, ramonxm commented on src/mocks/DescriptionProfile.mock.ts
> +  {
Pode ter uma propriedade `key` e se utiliza no lugar do index no map

2022-03-02 17:42 UTC, jonataspinto requested changes

2022-03-02 17:42 UTC, jonataspinto commented on src/components/StudentProfile/styles.ts
> +  height: 532px;
Faz sentido limitar a altura?

2022-03-02 17:42 UTC, jonataspinto commented on src/components/StudentProfile/styles.ts
> +  variant: 'subtitle1',
As variantes que existiam não atendem?

2022-03-02 17:42 UTC, jonataspinto commented on src/components/StudentProfile/styles.ts
> +  margin: 20px 0;
Para 24px são 2rem.

2022-03-02 17:42 UTC, jonataspinto commented on src/components/StudentProfile/styles.ts
> +  margin-bottom: 80px;
Rem

2022-03-03 04:42 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.63 | ✅ |
| First Contentful Paint | 3.4 s |  |
| Time to Interactive | 5.1 s |  |
| Speed Index | 3.9 s |  |
| Total Blocking Time | 370 ms |  |
| Largest Contentful Paint | 5.5 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.95 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.4 s |  |
| Speed Index | 2.8 s |  |
| Total Blocking Time | 130 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-03-03 04:43 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-62-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-94-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-03 10:51 UTC, jonataspinto approved these changes
Boa! Só ficou uma coisa para corrigir mas vou deixar o approve já

2022-03-03 10:51 UTC, jonataspinto commented on src/components/StudentProfile/index.tsx
> +import { studentProfileSection } from '../../mocks/DescriptionProfile.mock';
Não é mais usado aqui né?

2022-03-03 15:11 UTC, joaoprferreira commented
Estava dando uma investigada relacionado ao score, e realizei uns testes.

- score atual 
- 
![atual](https://user-images.githubusercontent.com/49590645/156592312-182f4618-0cc8-4fea-a3d9-7f0a3e8ebe6a.png)

Retirei algumas imagens e fui acompanhando o score, a que mais elevou o score foi quando removi o background do header

- score sem imagem do header 

![sem a image do header](https://user-images.githubusercontent.com/49590645/156592891-31adff5c-b750-4f9d-b279-2cb2c6badc90.png)

2022-03-03 15:16 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.53 | ✅ |
| First Contentful Paint | 3.8 s |  |
| Time to Interactive | 6.2 s |  |
| Speed Index | 4.5 s |  |
| Total Blocking Time | 590 ms |  |
| Largest Contentful Paint | 5.1 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.95 | ✅ |
| First Contentful Paint | 1.6 s |  |
| Time to Interactive | 5.3 s |  |
| Speed Index | 2.5 s |  |
| Total Blocking Time | 130 ms |  |
| Largest Contentful Paint | 2.0 s |  |
| Cumulative Layout Shift | 0.042 |  |

    
</details>

2022-03-03 15:16 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-93-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-95-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-03 17:32 UTC, merged