Feature/how we do
estartando-devs/site pull request #59
Opened 2022-03-03 02:58 UTC by yagovaluchedevs

### [Ticket]() | [Mocks]()

## Description

Criando a seção Como nós fazemos

## Dev Notes

- If any developer notes are required, list them here. If not, remove the 'Notes' section.

## Testing

### Steps

1. List all steps in a numbered list

## Screenshots / Videos

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-03-03 10:46 UTC, jonataspinto requested changes
Fala mano, iria colocar review em cada ponto mas é muita coisa.

- Resolver conflitos
- Usar medidas relativas
- As imagens estão na descrição da tarefa no Trello, caso não estejam me dá um alô que coloco.
- Ao invés de ter `jsx` explícito em cada texto de destaque, podemos usar o `dangernousInnerHtml` e passar uma string com toda formatação necessária igual no pr #58

2022-03-03 17:10 UTC, ramonxm commented
Essa branch ta rolando um scroll horizontal
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/38158476/156615393-ea9f61d2-508e-415d-a098-387ae5954864.png">

2022-03-03 17:15 UTC, ramonxm requested changes

2022-03-04 13:05 UTC, ramonxm requested changes

2022-03-04 13:05 UTC, ramonxm commented on src/mocks/listTextHowWeDo.mock.ts
> +  ` Nossa proposta de ensino coloca o aluno como protagonista.
Pra se assemelhar ao uso do CMS ele vem como um objeto ou array de objetos

Seria interessante deixar nesse formato: https://github.com/estartando-devs/site/blob/develop/src/mocks/DescriptionProfile.mock.ts

2022-03-04 13:05 UTC, ramonxm commented on src/components/StudentCharacteristicsCard/styles.ts
> +}
ainda persisti

2022-03-04 13:05 UTC, ramonxm commented on src/components/StudentCharacteristicsCard/styles.ts
> +  box-shadow: -0.25rem -0.125rem 0.312rem -0.375rem white;
o white tem no tema tbm

2022-03-04 13:05 UTC, ramonxm commented on src/components/StudentCharacteristicsCard/styles.ts
>    background-color: #1e1e1e;
tem no tema

2022-03-04 13:05 UTC, ramonxm commented on src/components/StudentCharacteristicsCard/styles.ts
>    background-color: #7b7a7a;
esse n tem, vale botar lá

2022-03-04 13:15 UTC, ramonxm commented
@yagovaluchedevs da uma olhada no files porque a resolução de conflitos trouxe muitos arquivos antigos que já foram deletados e alterados

2022-03-04 13:38 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.64 | ✅ |
| First Contentful Paint | 3.1 s |  |
| Time to Interactive | 4.8 s |  |
| Speed Index | 3.4 s |  |
| Total Blocking Time | 470 ms |  |
| Largest Contentful Paint | 5.3 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.9 | ✅ |
| First Contentful Paint | 2.1 s |  |
| Time to Interactive | 6.2 s |  |
| Speed Index | 2.9 s |  |
| Total Blocking Time | 120 ms |  |
| Largest Contentful Paint | 2.5 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-03-04 13:38 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-93-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-94-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-04 14:06 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.52 | ✅ |
| First Contentful Paint | 3.2 s |  |
| Time to Interactive | 6.3 s |  |
| Speed Index | 3.9 s |  |
| Total Blocking Time | 810 ms |  |
| Largest Contentful Paint | 4.9 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.92 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.7 s |  |
| Speed Index | 2.9 s |  |
| Total Blocking Time | 260 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-03-04 14:06 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-80-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-91-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-04 14:23 UTC, ramonxm requested changes

2022-03-04 16:34 UTC, ramonxm commented
@yagovaluchedevs da um git pull ai, falta remover os conflitos.

2022-03-04 17:32 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-96-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-95-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-04 17:37 UTC, ramonxm commented
Mobile ta meio zoado 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/38158476/156813707-45aa60fa-5860-4ba1-998a-ca4fa9188009.png">

2022-03-04 17:42 UTC, ramonxm requested changes

2022-03-04 17:42 UTC, ramonxm commented on src/components/HowWeDo/styles.ts
> +const TitleHowWeDo = styled.h1`
2.25 rem é o `h2` do tema, usa o typography.

2022-03-04 17:42 UTC, ramonxm commented on src/components/StudentCharacteristicsCard/index.tsx
> +        width="46px"
pode ser `width={46}`

2022-03-04 17:47 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.62 | ✅ |
| First Contentful Paint | 3.0 s |  |
| Time to Interactive | 4.2 s |  |
| Speed Index | 3.8 s |  |
| Total Blocking Time | 560 ms |  |
| Largest Contentful Paint | 5.1 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.91 | ✅ |
| First Contentful Paint | 2.1 s |  |
| Time to Interactive | 5.6 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 140 ms |  |
| Largest Contentful Paint | 2.5 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-03-04 17:47 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-87-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-92-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-04 20:11 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-93-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-83-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-04 20:11 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.65 | ✅ |
| First Contentful Paint | 3.3 s |  |
| Time to Interactive | 4.9 s |  |
| Speed Index | 3.9 s |  |
| Total Blocking Time | 440 ms |  |
| Largest Contentful Paint | 4.8 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 2.0 s |  |
| Time to Interactive | 5.0 s |  |
| Speed Index | 2.8 s |  |
| Total Blocking Time | 120 ms |  |
| Largest Contentful Paint | 2.1 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-03-04 20:11 UTC, jonataspinto commented on src/components/HowWeDo/styles.ts
> +const TitleHowWeDo = styled.h1`
VAleu

2022-03-04 20:11 UTC, jonataspinto commented
> Mobile ta meio zoado
> 
> <img alt="image" width="299" src="https://user-images.githubusercontent.com/38158476/156813707-45aa60fa-5860-4ba1-998a-ca4fa9188009.png">

Corrigido!

2022-03-04 20:14 UTC, jonataspinto approved these changes

2022-03-04 20:14 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.66 | ✅ |
| First Contentful Paint | 3.1 s |  |
| Time to Interactive | 4.9 s |  |
| Speed Index | 3.5 s |  |
| Total Blocking Time | 440 ms |  |
| Largest Contentful Paint | 4.9 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.91 | ✅ |
| First Contentful Paint | 2.1 s |  |
| Time to Interactive | 6.0 s |  |
| Speed Index | 2.8 s |  |
| Total Blocking Time | 110 ms |  |
| Largest Contentful Paint | 2.5 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

2022-03-04 20:15 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-84-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-22-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-92-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-04 20:42 UTC, merged

2022-03-04 20:43 UTC, ramonxm approved these changes