Chore: Implementing animation, to show the content.
estartando-devs/site pull request #92
Opened 2022-03-12 23:12 UTC by Junior331

### [Ticket]() | [Mocks]()

## Description

Provide a description of what was changed and why it was implemented this way.

## Dev Notes

- If any developer notes are required, list them here. If not, remove the 'Notes' section.

## Testing

### Steps

1. List all steps in a numbered list

## Screenshots / Videos

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

2022-03-12 23:16 UTC, jonataspinto commented
Deu ruim no build

@Junior331

2022-03-13 01:05 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.69 | ✅ |
| First Contentful Paint | 1.9 s |  |
| Time to Interactive | 5.5 s |  |
| Speed Index | 3.2 s |  |
| Total Blocking Time | 1,380 ms |  |
| Largest Contentful Paint | 2.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.89 | ✅ |
| First Contentful Paint | 2.4 s |  |
| Time to Interactive | 6.2 s |  |
| Speed Index | 2.9 s |  |
| Total Blocking Time | 110 ms |  |
| Largest Contentful Paint | 2.7 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-13 01:05 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-90-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-85-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-13 01:09 UTC, Junior331 commented
> Deu ruim no build
> 
> @Junior331

Resolvido.

2022-03-13 01:48 UTC, jonataspinto requested changes
A seção de nossos resultados ficou com um pequeno bug no mobile. Vidas transformadas não aparece

2022-03-13 01:55 UTC, jonataspinto requested changes

2022-03-13 01:55 UTC, jonataspinto commented on src/mocks/DescriptionProfile.mock.ts
> +  dataAos: string;
A ideia desses mocks é deixar isolado toda parte de dados, pensando em controlar vida CMS um dia. Acho que esses dados relacionados ao `aos` não cabem aqui.

2022-03-13 01:55 UTC, jonataspinto commented on src/pages/index.tsx
> +  useEffect(() => {
Podemos implementar um hook para isso, o que acha @Junior331 ?

2022-03-17 13:54 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-82-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-83-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-17 18:12 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-82-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-81-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-17 18:12 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.71 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 7.5 s |  |
| Speed Index | 2.9 s |  |
| Total Blocking Time | 890 ms |  |
| Largest Contentful Paint | 2.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.79 | ✅ |
| First Contentful Paint | 2.6 s |  |
| Time to Interactive | 7.2 s |  |
| Speed Index | 4.1 s |  |
| Total Blocking Time | 210 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-17 18:32 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 1.2 s |  |
| Time to Interactive | 6.3 s |  |
| Speed Index | 1.7 s |  |
| Total Blocking Time | 160 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.87 | ✅ |
| First Contentful Paint | 2.3 s |  |
| Time to Interactive | 6.5 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 120 ms |  |
| Largest Contentful Paint | 2.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-17 18:32 UTC, jonataspinto reviewed
![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-89-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-56-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

![](https://img.shields.io/badge/Accessibility-97-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-83-orange?style=flat-square) ![](https://img.shields.io/badge/Performance-89-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-60-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-100-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/","mobile:http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/"]COMMENT_ID -->

2022-03-17 19:06 UTC, jonataspinto commented
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.91 | ✅ |
| First Contentful Paint | 1.4 s |  |
| Time to Interactive | 6.6 s |  |
| Speed Index | 2.0 s |  |
| Total Blocking Time | 250 ms |  |
| Largest Contentful Paint | 1.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.82 | ✅ |
| First Contentful Paint | 2.6 s |  |
| Time to Interactive | 7.0 s |  |
| Speed Index | 4.0 s |  |
| Total Blocking Time | 160 ms |  |
| Largest Contentful Paint | 2.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

2022-03-17 19:10 UTC, merged